language: go
install: go get -v github.com/spf13/hugo
script:
  - hugo
  - python --version
  - sudo pip install s3cmd
  - s3cmd sync --delete-removed -P -M -r public/ s3://aws-website-ssha-o06c3/
notifications:
    email:
        on_failure: always
secure: "iMnzUQKGtdUVcY1znRnLnYfhjphGoLLJmDxuwNHxi0bm826oGl3PvIPWqmQc1Un6MTXdfXluX0eouoVID1x4lod8R9AkNGAIQcBsQ0SKDMKp9DkYmyq+oFcUSaQqZ3tiTWrERJsFQRYDgvMNe6ukbIW1FpoWohN2Q5ABWjYYkijrLY6cMPq0fiJjazXi2xoZH9bY86YCMdZM5uqHn/Bz6Le4cx2/Z+j9f0ynMTLHs6w/Dvnv4/Wy+0ixwyXUjJoaMNZBVZtwNkGTOo/42WvbHWJGpNtn++/WrjQNcOzA4LX+olKJLi4ARxn6guSZ3Xs4KZ8XbRdeJFyikvB8I3YL7tco3cQT17qEf23iZZVWqO3V77E49S2w0mpsVCW8SClFmrZnkr4nLA/TQ4QxxUdxk1EGjgMZvOIxt12jj8Ey8EWKU8vI05X7UZhp+QhMyUA14QX+wlED9GBuI/rr4nbYuB+cQymiGf3n6H49edITsw/VoXLOO6ez7Il2O2bqIBtfvVAhPFbQys/khs7A430e3a8TtIQD8YzxEix83l0lJhFtY0WwwMwBmacWRt80xWt5kUOyJF6RYDhHmaAmBpd+Q+Rqar0o86dZiUhABv/s7CTha7yoo1TewDo/0oYDgeNF+5ssLtXchBuenNOcU+bLjGTqndEVUVYxjklScjglsis="
secure: "KUn6lVEFErriMJgMX+kI9j/wyXG1CGb9e06kcb3Vh86au0OpvLxpAp39mkKjesRmvqwiIeid4OQNA0uO05+hajQ/MO7p0xqd0PegwgobLKvaR6M3AZHRCOeHY3IHtq82v80huOOD477QqYnPX7eus0sLLOisEcLSBmQs+F6mOOKsPEwW9tEODJPNlAJXna8YQ0tcIU3JVhiSVNC9OHJ/cToC0n4WwPjtj3czOw6aI/pxzlNTu+4AyXDdT1xsY/IMKWhC/XQp4qcAfLIqoGqMpaUsPCn37H8iSsKgvCBqkMGewFbJIyd0eDfyMNp4AzAlqjkbgxjK5LtvXqNaHpRhLA5UVoqEWcUpEcTgHnex/drmG1qlj3oHeN0TXlcnR+fV4biPxkNte5Iv4XadHGB0ZqQQhP2lIREYb8RaDwbUgSJ5aYabjtH56am1IN3XPewj7FYBpPvADwjVAosUk0Aa8pzNnJczUbnYYTewz+qKv4fNDcp8w1hD+K2A77EWR0pmjlyNn6WJH+bZ7zExe5EmZ0W0GLxaUn66KAJLWJQ17G50EHeA0sV1Bm53WDop6+1VsRvAVPPZMtWs/gBMXVrL2d7zN9X1tuEdlcyVMfwy+Clb7jQuak1Tqmh0bnCmfO8csKJ3yB3Uo8I4FT37CkhkQy4n3QiFdvFZz6ce7DPzZy4="

